(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const DB='EtikTemplatesDB',STORE='templates',FORMAT='etik-template',VERSION=1,PARAM='etik',MAX_LINK_BYTES=7000;
let dbp,incoming=null,sharing=null;

const css=document.createElement('style');css.textContent=`
.etik-tpl-count{font-size:.72rem;opacity:.6;margin-left:4px}.etik-tpl-launch{display:flex;gap:7px;margin-top:8px}.etik-tpl-launch .btn{flex:1}
.etik-tpl-overlay{position:fixed;inset:0;z-index:14000;background:rgba(0,0,0,.42);display:none;align-items:center;justify-content:center;padding:16px;backdrop-filter:blur(2px)}.etik-tpl-overlay.open{display:flex}
.etik-tpl-dialog{width:min(680px,100%);max-height:92vh;background:var(--paper,#fff);color:var(--ink,#171717);border:1px solid var(--line,#ddd);border-radius:18px;box-shadow:0 24px 70px rgba(0,0,0,.24);display:flex;flex-direction:column;overflow:hidden;position:relative}
.etik-tpl-head{display:flex;align-items:center;gap:10px;padding:13px 14px;border-bottom:1px solid var(--line,#ddd)}.etik-tpl-head .title{min-width:0;flex:1}.etik-tpl-head strong{display:block}.etik-tpl-head small{display:block;color:var(--muted,#777);margin-top:2px}.etik-tpl-close{width:38px;height:38px;min-width:38px;padding:0!important;display:grid!important;place-items:center;font-size:1.15rem}
.etik-tpl-body{overflow:auto;padding:12px}.etik-tpl-save{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:7px;margin-bottom:10px}.etik-tpl-save input,.etik-tpl-search{width:100%;min-width:0;min-height:42px;padding:9px 11px;border:1px solid var(--line,#ddd);border-radius:10px;background:#fff;color:#111;font:inherit}.etik-tpl-search{margin-bottom:9px}
.etik-tpl-incoming{display:none;padding:11px;border:1px solid rgba(18,101,214,.25);background:rgba(18,101,214,.07);border-radius:12px;margin-bottom:10px}.etik-tpl-incoming.show{display:block}.etik-tpl-incoming p{font-size:.78rem;line-height:1.4;color:var(--muted,#666);margin:5px 0 9px}.etik-tpl-incoming .actions{display:flex;gap:6px;flex-wrap:wrap}
.etik-tpl-list{display:grid;gap:8px}.etik-tpl-empty{padding:26px 15px;text-align:center;border:1px dashed var(--line,#ddd);border-radius:12px;color:var(--muted,#777);font-size:.82rem}.etik-tpl-card{display:grid;grid-template-columns:40px minmax(0,1fr) auto;align-items:center;gap:9px;padding:9px;border:1px solid var(--line,#ddd);border-radius:12px}.etik-tpl-card .ico{width:40px;height:40px;border-radius:10px;background:rgba(18,101,214,.08);display:grid;place-items:center}.etik-tpl-info{min-width:0}.etik-tpl-info strong{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.etik-tpl-info small{display:block;color:var(--muted,#777);font-size:.68rem;margin-top:3px}.etik-tpl-actions{display:flex;gap:5px}.etik-tpl-actions .btn{min-width:36px;height:36px;padding:0 9px!important;display:grid!important;place-items:center}.etik-tpl-foot{display:flex;justify-content:space-between;gap:8px;margin-top:10px;padding-top:10px;border-top:1px solid var(--line,#ddd);font-size:.68rem;color:var(--muted,#777)}
.etik-share{position:absolute;inset:0;z-index:2;background:var(--paper,#fff);display:none;flex-direction:column}.etik-share.open{display:flex}.etik-share-body{overflow:auto;padding:15px}.etik-share-preview{text-align:center;padding:8px}.etik-share-preview .ico{width:56px;height:56px;margin:0 auto 8px;border-radius:15px;background:rgba(18,101,214,.09);display:grid;place-items:center;font-size:1.5rem}.etik-share-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.etik-share-actions .btn{min-height:43px}.etik-share-note{margin-top:10px;padding:10px;border:1px solid var(--line,#ddd);border-radius:10px;font-size:.75rem;line-height:1.4;color:var(--muted,#666)}.etik-share-qr{display:none;text-align:center;margin-top:12px;padding:11px;border:1px solid var(--line,#ddd);border-radius:12px;background:#fff}.etik-share-qr.show{display:block}.etik-share-qr canvas{width:min(230px,100%);height:auto}
.etik-tpl-toast{position:fixed;z-index:15000;left:50%;bottom:max(22px,env(safe-area-inset-bottom));transform:translate(-50%,16px);background:#20272f;color:#fff;padding:10px 13px;border-radius:10px;font-size:.77rem;opacity:0;pointer-events:none;transition:.18s ease;max-width:calc(100vw - 24px);text-align:center}.etik-tpl-toast.show{opacity:1;transform:translate(-50%,0)}
@media(max-width:760px){.etik-tpl-overlay{align-items:flex-end;padding:0}.etik-tpl-dialog{width:100%;max-height:88dvh;border-radius:18px 18px 0 0;border-left:0;border-right:0;border-bottom:0}.etik-tpl-body{padding:10px 10px calc(16px + env(safe-area-inset-bottom))}.etik-tpl-save{grid-template-columns:minmax(0,1fr) auto}.etik-tpl-save .import{grid-column:1/-1}.etik-tpl-card{grid-template-columns:38px minmax(0,1fr)}.etik-tpl-actions{grid-column:1/-1;justify-content:flex-end;border-top:1px solid var(--line,#eee);padding-top:7px}.etik-share-actions{grid-template-columns:1fr}}
`;document.head.appendChild(css);

function openDb(){if(dbp)return dbp;dbp=new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{const d=q.result;if(!d.objectStoreNames.contains(STORE)){const s=d.createObjectStore(STORE,{keyPath:'id'});s.createIndex('updatedAt','updatedAt')}};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)});return dbp}
async function put(v){const d=await openDb();await new Promise((res,rej)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(v);t.oncomplete=res;t.onerror=()=>rej(t.error)});navigator.storage?.persist?.().catch(()=>{})}
async function del(id){const d=await openDb();await new Promise((res,rej)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).delete(id);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
async function all(){const d=await openDb();return new Promise((res,rej)=>{const t=d.transaction(STORE),q=t.objectStore(STORE).getAll();q.onsuccess=()=>res((q.result||[]).sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0)));q.onerror=()=>rej(q.error)})}
const id=()=>crypto.randomUUID?.()||`etik-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
const safe=n=>String(n||'Plantilla Etik').trim().replace(/[\\/:*?"<>|]+/g,'-').slice(0,80)||'Plantilla Etik';
const defaultName=()=>`Plantilla ${new Intl.DateTimeFormat('es-MX').format(new Date())}`;
function normalize(v,name='Plantilla Etik'){if(v?.format===FORMAT&&v.version)return{...v,id:v.id||id(),name:safe(v.name||name),createdAt:v.createdAt||Date.now(),updatedAt:v.updatedAt||Date.now()};return{format:FORMAT,version:VERSION,id:id(),name:safe(name),createdAt:Date.now(),updatedAt:Date.now(),design:v}}

async function capture(){const b=$('#exportBtn');if(!b)throw Error('No se encontró el exportador de Etik.');let blob=null,href='';const oc=URL.createObjectURL?.bind(URL),oa=HTMLAnchorElement.prototype.click;try{if(oc)URL.createObjectURL=o=>{if(o instanceof Blob)blob=o;return oc(o)};HTMLAnchorElement.prototype.click=function(){href=this.href||''};b.click();await new Promise(r=>setTimeout(r,80))}finally{if(oc)URL.createObjectURL=oc;HTMLAnchorElement.prototype.click=oa}let text='';if(blob)text=await blob.text();else if(href.startsWith('data:')){const i=href.indexOf(','),meta=href.slice(0,i),body=href.slice(i+1);text=/;base64/i.test(meta)?decodeURIComponent(escape(atob(body))):decodeURIComponent(body)}if(!text)throw Error('No se pudo capturar el diseño actual.');return JSON.parse(text)}
async function apply(design){const inp=$('#importDesignFile');if(!inp||typeof DataTransfer==='undefined')throw Error('Este navegador no permite abrir la plantilla automáticamente.');const f=new File([typeof design==='string'?design:JSON.stringify(design)],'etik-template.json',{type:'application/json'}),dt=new DataTransfer();dt.items.add(f);inp.files=dt.files;inp.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,120))}
function fileOf(t){return new File([JSON.stringify(t,null,2)],`${safe(t.name).replace(/\s+/g,'-').toLowerCase()}.etik`,{type:'application/vnd.etik+json'})}
function download(t){const f=fileOf(t),u=URL.createObjectURL(f),a=document.createElement('a');a.href=u;a.download=f.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function b64(bytes){let x='';for(let i=0;i<bytes.length;i+=32768)x+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(x).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function fromB64(v){let s=v.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a}
function shareLink(t){const c={...t};delete c.id;const bytes=new TextEncoder().encode(JSON.stringify(c));if(bytes.length>MAX_LINK_BYTES)return null;const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set(PARAM,b64(bytes));return u.toString()}
function incomingUrl(){try{const u=new URL(location.href),x=u.searchParams.get(PARAM);if(!x)return null;return normalize(JSON.parse(new TextDecoder().decode(fromB64(x))),'Plantilla compartida')}catch(e){console.warn(e);return null}}
function clearIncoming(){const u=new URL(location.href);u.searchParams.delete(PARAM);history.replaceState(null,'',u.pathname+(u.search||'')+u.hash)}

const toast=document.createElement('div');toast.className='etik-tpl-toast';document.body.appendChild(toast);let tt;function note(s){clearTimeout(tt);toast.textContent=s;toast.classList.add('show');tt=setTimeout(()=>toast.classList.remove('show'),2200)}
const ov=document.createElement('div');ov.className='etik-tpl-overlay';ov.innerHTML=`<section class="etik-tpl-dialog" role="dialog" aria-modal="true"><div class="etik-tpl-head"><div style="font-size:1.25rem">▤</div><div class="title"><strong>Mis plantillas</strong><small>Biblioteca local de Etik</small></div><button class="btn etik-tpl-close" id="etikTplClose">×</button></div><div class="etik-tpl-body"><div class="etik-tpl-incoming" id="etikTplIncoming"><strong id="etikTplIncomingName">Plantilla compartida</strong><p>Esta plantilla llegó mediante un enlace de Etik.</p><div class="actions"><button class="btn primary" id="etikTplIncomingOpen">Abrir</button><button class="btn" id="etikTplIncomingSave">Guardar</button><button class="btn" id="etikTplIncomingDismiss">Ignorar</button></div></div><div class="etik-tpl-save"><input id="etikTplName" maxlength="80" placeholder="Nombre de la plantilla"><button class="btn primary" id="etikTplSave">＋ Guardar actual</button><button class="btn import" id="etikTplImport">⇧ Importar .etik</button><input id="etikTplFile" type="file" accept=".etik,.json,application/json,application/vnd.etik+json" hidden></div><input class="etik-tpl-search" id="etikTplSearch" type="search" placeholder="Buscar plantillas…"><div class="etik-tpl-list" id="etikTplList"></div><div class="etik-tpl-foot"><span>Guardadas en este dispositivo</span><span>ETIK v1</span></div></div><div class="etik-share" id="etikShare"><div class="etik-tpl-head"><button class="btn etik-tpl-close" id="etikShareBack">‹</button><div class="title"><strong>Compartir plantilla</strong><small>Archivo, enlace o QR</small></div></div><div class="etik-share-body"><div class="etik-share-preview"><div class="ico">↗</div><strong id="etikShareName">Plantilla</strong><small>Compatible con Etik Web y Android</small></div><div class="etik-share-actions"><button class="btn primary" id="etikNativeShare">↗ Compartir</button><button class="btn" id="etikDownload">⇩ Descargar .etik</button><button class="btn" id="etikCopyLink">🔗 Copiar enlace</button><button class="btn" id="etikShowQr">▦ Mostrar QR</button></div><div class="etik-share-note" id="etikShareNote"></div><div class="etik-share-qr" id="etikQrWrap"><canvas id="etikQrCanvas"></canvas><div style="font-size:.68rem;color:#666;margin-top:6px">Escanea para abrir esta plantilla en Etik.</div></div></div></div></section>`;document.body.appendChild(ov);
const list=$('#etikTplList'),search=$('#etikTplSearch'),inc=$('#etikTplIncoming');
function openLib(){ov.classList.add('open');document.body.dataset.etikTplOverflow=document.body.style.overflow||'';document.body.style.overflow='hidden';render()}
function closeLib(){$('#etikShare').classList.remove('open');ov.classList.remove('open');document.body.style.overflow=document.body.dataset.etikTplOverflow||''}
const date=n=>{try{return new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(n))}catch{return new Date(n).toLocaleString()}};
async function count(){try{const n=(await all()).length;$$('.etik-tpl-count').forEach(e=>e.textContent=n)}catch{}}
async function render(){const q=(search.value||'').trim().toLocaleLowerCase('es'),rows=(await all()).filter(t=>!q||t.name.toLocaleLowerCase('es').includes(q));if(!rows.length){list.innerHTML=`<div class="etik-tpl-empty">${q?'No encontré plantillas con ese nombre.':'Aún no tienes plantillas guardadas.<br><br>Diseña algo y toca <strong>Guardar actual</strong>.'}</div>`;count();return}list.innerHTML='';rows.forEach(t=>{const c=document.createElement('div');c.className='etik-tpl-card';c.dataset.id=t.id;c.innerHTML=`<div class="ico">▤</div><div class="etik-tpl-info"><strong></strong><small></small></div><div class="etik-tpl-actions"><button class="btn primary" data-a="open">Abrir</button><button class="btn" data-a="share" title="Compartir">↗</button><button class="btn" data-a="copy" title="Duplicar">⧉</button><button class="btn danger" data-a="delete" title="Eliminar">⌫</button></div>`;$('.etik-tpl-info strong',c).textContent=t.name;$('.etik-tpl-info small',c).textContent=`Actualizada ${date(t.updatedAt)}`;list.appendChild(c)});count()}
async function saveCurrent(){const b=$('#etikTplSave'),inp=$('#etikTplName'),old=b.textContent;b.disabled=true;b.textContent='Guardando…';try{const now=Date.now(),t=normalize({format:FORMAT,version:VERSION,id:id(),name:safe(inp.value||defaultName()),createdAt:now,updatedAt:now,design:await capture()});await put(t);inp.value='';await render();note('Plantilla guardada.')}catch(e){console.error(e);note(e.message||'No se pudo guardar.')}finally{b.disabled=false;b.textContent=old}}
async function copyText(x){try{await navigator.clipboard.writeText(x);return true}catch{const t=document.createElement('textarea');t.value=x;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();const ok=document.execCommand('copy');t.remove();return ok}}
function showShare(t){sharing=t;$('#etikShare').classList.add('open');$('#etikShareName').textContent=t.name;$('#etikQrWrap').classList.remove('show');const l=shareLink(t),n=$('#etikShareNote');$('#etikCopyLink').disabled=!l;$('#etikShowQr').disabled=!l;n.innerHTML=l?'El enlace contiene la plantilla completa y <strong>no requiere cuenta ni servidor</strong>.':'Esta plantilla es demasiado grande para un enlace seguro. <strong>Compártela como archivo .etik</strong>.'}
async function nativeShare(t){const f=fileOf(t),l=shareLink(t);try{if(navigator.share&&navigator.canShare?.({files:[f]})){await navigator.share({title:`Etik · ${t.name}`,text:'Plantilla de Etik',files:[f]});return}if(navigator.share&&l){await navigator.share({title:`Etik · ${t.name}`,text:'Abre esta plantilla en Etik',url:l});return}download(t);note('Archivo .etik descargado.')}catch(e){if(e?.name!=='AbortError')console.error(e)}}
async function showQr(t){const l=shareLink(t);if(!l)return;try{if(window.QRCode?.toCanvas){await QRCode.toCanvas($('#etikQrCanvas'),l,{width:240,margin:2,errorCorrectionLevel:'M'});$('#etikQrWrap').classList.add('show')}else note('El motor QR aún no está disponible.')}catch(e){console.error(e);note('No se pudo generar el QR.')}}
async function importFile(f){const p=JSON.parse(await f.text()),t=normalize(p,f.name.replace(/\.(etik|json)$/i,'')||'Plantilla importada');t.id=id();t.createdAt=t.updatedAt=Date.now();await put(t);await render();note('Plantilla importada.')}

list.addEventListener('click',async e=>{const b=e.target.closest('[data-a]'),c=e.target.closest('.etik-tpl-card');if(!b||!c)return;const t=(await all()).find(x=>x.id===c.dataset.id);if(!t)return;switch(b.dataset.a){case'open':try{await apply(t.design);closeLib();note(`Abierta: ${t.name}`)}catch(x){note(x.message)}break;case'share':showShare(t);break;case'copy':await put({...t,id:id(),name:`${t.name} · copia`,createdAt:Date.now(),updatedAt:Date.now()});await render();note('Plantilla duplicada.');break;case'delete':if(confirm(`¿Eliminar “${t.name}”?`)){await del(t.id);await render();note('Plantilla eliminada.')}break}});
$('#etikTplClose').onclick=closeLib;ov.addEventListener('click',e=>{if(e.target===ov)closeLib()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&ov.classList.contains('open'))closeLib()});$('#etikTplSave').onclick=saveCurrent;$('#etikTplImport').onclick=()=>$('#etikTplFile').click();$('#etikTplFile').onchange=async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{await importFile(f)}catch(x){console.error(x);note('Ese archivo no es una plantilla Etik válida.')}};search.oninput=render;
$('#etikShareBack').onclick=()=>$('#etikShare').classList.remove('open');$('#etikNativeShare').onclick=()=>sharing&&nativeShare(sharing);$('#etikDownload').onclick=()=>{if(sharing){download(sharing);note('Archivo .etik descargado.')}};$('#etikCopyLink').onclick=async()=>{const l=sharing&&shareLink(sharing);if(l)note(await copyText(l)?'Enlace copiado.':'No se pudo copiar.')};$('#etikShowQr').onclick=()=>sharing&&showQr(sharing);

const drawer=$('.etik-drawer-scroll');if(drawer&&!$('#etikTemplatesMenuCard')){const c=document.createElement('div');c.className='etik-menu-card';c.id='etikTemplatesMenuCard';c.innerHTML=`<details><summary>▤ Plantillas <span class="etik-tpl-count">0</span></summary><div class="etik-menu-card-content"><p>Guarda diseños reutilizables, impórtalos como <strong>.etik</strong> y compártelos por archivo, enlace o QR.</p><div class="etik-tpl-launch"><button class="btn primary" id="etikOpenLibrary">Abrir biblioteca</button><button class="btn" id="etikQuickSave">Guardar actual</button></div></div></details>`;const contact=$$('.etik-menu-card',drawer).find(x=>x.textContent.includes('Contacto'));drawer.insertBefore(c,contact||null);$('#etikOpenLibrary').onclick=openLib;$('#etikQuickSave').onclick=()=>{openLib();requestAnimationFrame(()=>$('#etikTplName').focus())}}
const mobile=$('#mobileMoreMenu');if(mobile&&!$('#etikMobileTemplates')){const b=document.createElement('button');b.className='btn';b.id='etikMobileTemplates';b.textContent='▤ Mis plantillas';b.onclick=openLib;mobile.appendChild(b)}
const about=$$('.etik-menu-card-content p').find(p=>p.textContent.includes('Puedes agregar y editar texto'));if(about&&!about.textContent.includes('plantillas'))about.textContent+=' También puedes guardar diseños como plantillas y compartirlos entre dispositivos.';

$('#etikTplIncomingOpen').onclick=async()=>{if(!incoming)return;try{await apply(incoming.design);incoming=null;inc.classList.remove('show');clearIncoming();closeLib();note('Plantilla compartida abierta.')}catch(e){note(e.message)}};$('#etikTplIncomingSave').onclick=async()=>{if(!incoming)return;incoming.id=id();incoming.createdAt=incoming.updatedAt=Date.now();await put(incoming);incoming=null;inc.classList.remove('show');clearIncoming();await render();note('Plantilla compartida guardada.')};$('#etikTplIncomingDismiss').onclick=()=>{incoming=null;inc.classList.remove('show');clearIncoming()};
incoming=incomingUrl();if(incoming){$('#etikTplIncomingName').textContent=incoming.name;inc.classList.add('show');setTimeout(openLib,180)}count();
window.EtikTemplates=Object.freeze({format:FORMAT,version:VERSION,openLibrary:openLib,captureCurrentDesign:capture,applyDesign:apply,list:all,save:put,remove:del,normalize,makeShareLink:shareLink,download});
})();